### ISSUE TITLE
Change configration file format 

### ISSUE THREAD

**Issue by holyshared** [cloak-php/coveralls-kit#37]
```
service: travis-ci
reportFile:
    input:
        type: clover
        file: script/clover.xml
    output:
        script/coveralls.json
repositoryDirectory: .
```
